// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContexts():Promise<string>;

export function GetDashboardData():Promise<string>;
