// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContexts() {
  return window['go']['main']['App']['GetContexts']();
}

export function Nodes() {
  return window['go']['main']['App']['Nodes']();
}
